#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-snappy-java
Version  : 1.1.7.1
Release  : 2
URL      : https://github.com/xerial/snappy-java/archive/1.1.7.1.tar.gz
Source0  : https://github.com/xerial/snappy-java/archive/1.1.7.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar
Source2  : https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.pom
Source3  : https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1.jar
Source4  : https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: mvn-snappy-java-data = %{version}-%{release}

%description
This folder contains the native libraries built for various platforms.

%package data
Summary: data components for the mvn-snappy-java package.
Group: Data

%description data
data components for the mvn-snappy-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar
/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.pom
/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1.jar
/usr/share/java/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1.pom
